### PR TITLE
update pino to v8.3.1

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@Eomm

**Comment by Uzlopak** [comment]
It seems that pino-pretty is kind of flaky

**Comment by Uzlopak** [comment]
@mcollina 

Any Idea why the tests get flaky when using the pino-pretty transport?

**Comment by mcollina** [comment]
what's the error?

**Comment by mcollina** [comment]
I have no time to look into this.

**Comment by Uzlopak** [comment]
pino adds a listener to the exit event of the process when setting pino-pretty as transport. So I increased the timeout. So when all the tests are run, all the transports are killed, not resulting in the test failing.

**Comment by mcollina** [comment]
How is increasing the timeout fix the problem?

**Comment by Uzlopak** [comment]
I think the issue is the following:
You have 10 tests running. Each of them add a listener to process.exit, when using a pino transport. So when all tests pass in total 25 secs (default timeout), we pass. If one of them takes longer, the transport is still open. So the tests fail

**Review by Eomm — APPROVED** [review]

**Pull request merged**
