### PR TITLE
ci: enable license checking

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/workflows/issues/49

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Package "before-after-hook@2.2.2" is licensed under "Apache-2.0" which is not permitted by the --onlyAllow flag. Exiting.

https://github.com/fastify/workflows/pull/50

**Comment by Eomm** [comment]
new error

```
Package "tslib@2.4.0" is licensed under "0BSD" which is not permitted by the --onlyAllow flag. Exiting.
```

**Comment by Uzlopak** [comment]
@Fdawgs Can you modify something in this PR to enforce the use of the new workflow?

**Review by Uzlopak — APPROVED** [review]
I dont know if my review counts.

**Pull request merged**
