### PR TITLE
Update for Fastify v5

### PR DESCRIPTION
**Pull request by gurgunday**

### CODE REVIEW

**Comment by gurgunday** [comment]
I don't really get how, but a `proxyrequire` in one tests breaks another:

https://github.com/fastify/releasify/blob/0de5b403c74d71c47127b9958e7856a2da0570d5/test/command-config.test.js#L33-L44

These lines cause this test to fail:

https://github.com/fastify/releasify/blob/0de5b403c74d71c47127b9958e7856a2da0570d5/test/args.test.js#L67-L97

Error:

```sh

                       
  🌈 TEST COMPLETE 🌈  
                       

 FAIL  test/args.test.js 1 failed of 11 1.822s
 ✖  check default values > should be equivalent strictly
    test/args.test.js                                              
     68   t.plan(1)                                                
     69   const parsedArgs = parseArgs([])                         
     70                                                            
     71   t.strictSame(parsedArgs, {                               
     ━━━━━━━┛                                                      
     72     _: [],                                                 
     73     help: false,                                           
     74     arg: undefined,                                        
     75     path: process.cwd(),                                   
    --- expected                     
    +++ actual                       
    @@ -1,3 +1,3 @@                  
     Object {                        
    -  "semver": undefined,          
    +  "semver": "fake input string",
     }                               
```

**Comment by gurgunday** [comment]
@Eomm, do you know why dependency review fails? It seems to pass but returns a non-zero status code

**Review by jsumners — APPROVED** [review]
This module is independent of `fastify`. Update and release it according to normal process.

**Comment by Eomm** [comment]
I think it is due:
image


As already said: this plugin does not need to be bumped for v5 (TBH: it would require a lot of effort and till it works I would not touch it because I can't see the benefit over the time required)

**Comment by gurgunday** [comment]
Yeah the tests pass right now but there is def some flakyness

**Comment by gurgunday** [comment]
Tap is already at `v21` 🤦‍♂️, and another npm update breaks nearly everything

I agree that it's better to keep it working right now

**Pull request closed without merging**
